get card endpoint
GSG-G10/Team2 pull request #51
Opened 2021-10-04 12:15 UTC by muhammadharoun

2021-10-04 12:19 UTC, rawand1998 approved these changes

2021-10-04 17:55 UTC, mohammedsalah7 approved these changes

2021-10-04 21:58 UTC, Mu7ammadAbed requested changes

2021-10-04 21:58 UTC, Mu7ammadAbed commented on server/database/connection.js
> +    dburl = DB_URL;
why? you shouldn't do this

2021-10-04 21:58 UTC, Mu7ammadAbed commented on server/routes/getCard.js
> +    .then((result) => res.json((result.rows)))
```suggestion
    .then(({ rows }) => res.json(({ data: rows })))
```

2021-10-04 21:58 UTC, Mu7ammadAbed commented on server/routes/getCard.js
> +    .catch((err) => res.json({ err }));
```suggestion
    .catch((err) => next(err));
```

2021-10-04 21:58 UTC, Mu7ammadAbed commented on server/routes/addUser.js
> +          .then(() => res.status(201).json({ status: 'scusses' }))
```suggestion
          .then(() => res.status(201).json({ status: 'User created successfully' }))
```

2021-10-04 21:58 UTC, Mu7ammadAbed commented on server/routes/clearCard.js
> +  const { userId } = req.body;
This shouldn't be sent with the request body

2021-10-04 21:58 UTC, Mu7ammadAbed commented on server/routes/deleteCard.js
> +  const { userId, productId } = req.body;
The userId here shouldn't be sent from the request body

2021-10-05 08:47 UTC, mohammedsalah7 submitted a review, later dismissed

2021-10-05 08:49 UTC, Mu7ammadAbed commented on server/routes/index.js
> +router.delete('/deletecard/:userId/:productId', deleteCardHandler);
You shouldn't send the userId for these routes by params, you should take it from the cookies after verifying, even if you still didn't handle this middleware properly you should add it and make your controller prepared for it
```suggestion
router.get('/getcard/:userId', getCardHandler);
router.delete('/clearcard', clearCardHandler);
router.delete('/deletecard/:productId', deleteCardHandler);
```

2021-10-05 08:55 UTC, Mu7ammadAbed commented on server/routes/addCard.js
>      addCardQuery(userId, productId, quantity)
You need to change your functions and queries name from `card` to `cart`
```suggestion
    addCartQuery(userId, productId, quantity)
```

2021-10-05 08:55 UTC, Mu7ammadAbed commented on server/routes/clearCard.js
> +const clearCardHandler = (req, res) => {
```suggestion
const { clearCartQuery } = require('../database/queries');

const clearCartHandler = (req, res) => {
```

2021-10-05 08:55 UTC, Mu7ammadAbed commented on server/routes/clearCard.js
> +  clearCardQuery(parseInt(userId, 10))
```suggestion
  clearCartQuery(parseInt(userId, 10))
```

2021-10-05 08:55 UTC, Mu7ammadAbed commented on server/routes/clearCard.js
> +module.exports = clearCardHandler;
```suggestion
module.exports = clearCartHandler;
```

2021-10-05 08:55 UTC, Mu7ammadAbed commented on server/routes/deleteCard.js
> +module.exports = deleteCardHandler;
```suggestion
const { deleteCartQuery } = require('../database/queries');

const deleteCartHandler = (req, res) => {
  const { userId, productId } = req.params;
  deleteCartQuery(parseInt(userId, 10), parseInt(productId, 10))
    .then(() => res.status(202).json({ status: 'product delete successfully' }))
    .catch((err) => res.json({ err }));
};
module.exports = deleteCartHandler;
```

2021-10-05 08:55 UTC, Mu7ammadAbed commented on server/routes/getCard.js
> +module.exports = getCardHandler;
```suggestion
const { getCartQuery } = require('../database/queries');

const getCartHandler = (req, res, next) => {
  const { userId } = req.params;
  getCartQuery(parseInt(userId, 10))
    .then(({ rows }) => res.json(({ data: rows })))
    .catch((err) => res.json({ err }))
    .catch((err) => next(err));
};
module.exports = getCartHandler;
```

2021-10-05 08:55 UTC, Mu7ammadAbed commented on server/routes/index.js
> +const clearCardHandler = require('./clearCard');
```suggestion
const getCartHandler = require('./getCart');
const deleteCartHandler = require('./deleteCart');
const clearCartHandler = require('./clearCart');
```

2021-10-05 10:02 UTC, rawand1998 approved these changes

2021-10-05 10:36 UTC, Mu7ammadAbed commented on server/controllers/loginController.js
> +  console.log(id, name);
```suggestion
```

2021-10-05 10:36 UTC, Mu7ammadAbed commented on server/routes/clearCart.js
> +  const userId = req.user.id;
```suggestion
  const { id: userId } = req.user;
```

2021-10-05 10:36 UTC, Mu7ammadAbed commented on server/routes/deleteCart.js
> +  const userId = req.user.id;
```suggestion
  const { id: userId } = req.user;
```

2021-10-05 10:36 UTC, Mu7ammadAbed commented on server/routes/getCart.js
> +  const userId = req.user.id;
```suggestion
  const { id: userId } = req.user;
```

2021-10-05 10:50 UTC, rawand1998 submitted a review, later dismissed

2021-10-05 10:51 UTC, Mu7ammadAbed commented on server/database/queries/getCartQuery.js
> +    text: 'select * FROM cart where user_id = $1;',
```suggestion
    text: 'SELECT * FROM cart WHERE user_id = $1;',
```

2021-10-05 10:51 UTC, Mu7ammadAbed commented on server/database/queries/deleteCartQuery.js
> +    text: 'delete from cart where user_id =$1 AND product_id = $2;',
```suggestion
    text: 'DELETE FROM cart WHERE user_id =$1 AND product_id = $2;',
```

2021-10-05 10:51 UTC, Mu7ammadAbed commented on server/database/queries/clearCartQuery.js
> +    text: 'delete from cart where user_id = $1;',
```suggestion
    text: 'DELETE FROM cart WHERE user_id = $1;',
```

2021-10-05 10:53 UTC, NourAdawi submitted a review, later dismissed

2021-10-05 11:03 UTC, Mu7ammadAbed approved these changes

2021-10-05 11:03 UTC, merged